-- Seed data for enum_values
BEGIN;
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (1, 1, 'VALUE', NULL, 1, 'Scalar calibration value');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (2, 1, 'CURVE', NULL, 2, 'One-dimensional calibration curve');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (3, 1, 'MAP', NULL, 3, 'Two-dimensional calibration map');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (4, 1, 'CUBOID', NULL, 4, 'Three-dimensional calibration object');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (5, 1, 'CUBE_4', NULL, 5, 'Four-dimensional calibration object');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (6, 1, 'CUBE_5', NULL, 6, 'Five-dimensional calibration object');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (7, 2, 'UBYTE', NULL, 1, 'Unsigned 8-bit integer');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (8, 2, 'SBYTE', NULL, 2, 'Signed 8-bit integer');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (9, 2, 'UWORD', NULL, 3, 'Unsigned 16-bit integer');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (10, 2, 'SWORD', NULL, 4, 'Signed 16-bit integer');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (11, 2, 'ULONG', NULL, 5, 'Unsigned 32-bit integer');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (12, 2, 'SLONG', NULL, 6, 'Signed 32-bit integer');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (13, 2, 'A_UINT64', NULL, 7, 'Unsigned 64-bit integer');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (14, 2, 'A_INT64', NULL, 8, 'Signed 64-bit integer');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (15, 2, 'FLOAT16_IEEE', NULL, 9, 'IEEE 754 half-precision floating point');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (16, 2, 'FLOAT32_IEEE', NULL, 10, 'IEEE 754 single-precision floating point');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (17, 2, 'FLOAT64_IEEE', NULL, 11, 'IEEE 754 double-precision floating point');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (18, 3, 'MSB_FIRST', NULL, 1, 'Most significant byte first (big-endian)');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (19, 3, 'MSB_LAST', NULL, 2, 'Most significant byte last (little-endian)');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (20, 4, 'PBYTE', NULL, 1, 'Indirect addressing using a 1-byte pointer');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (21, 4, 'PWORD', NULL, 2, 'Indirect addressing using a 2-byte pointer');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (22, 4, 'PLONG', NULL, 3, 'Indirect addressing using a 4-byte pointer');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (23, 4, 'PLONGLONG', NULL, 4, 'Indirect addressing using an 8-byte pointer');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (24, 4, 'DIRECT', NULL, 5, 'Direct addressing');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (25, 5, 'INDEX_INCR', NULL, 1, 'Axis points stored in increasing index order');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (26, 5, 'INDEX_DECR', NULL, 2, 'Axis points stored in decreasing index order');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (27, 6, 'MON_DECREASE', NULL, 1, 'Monotonically decreasing');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (28, 6, 'MON_INCREASE', NULL, 2, 'Monotonically increasing');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (29, 6, 'STRICT_DECREASE', NULL, 3, 'Strictly monotonically decreasing');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (30, 6, 'STRICT_INCREASE', NULL, 4, 'Strictly monotonically increasing');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (31, 6, 'MONOTONOUS', NULL, 5, 'Monotonically increasing or decreasing');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (32, 6, 'STRICT_MON', NULL, 6, 'Strictly monotonically increasing or decreasing');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (33, 6, 'NOT_MON', NULL, 7, 'No monotonicity constraint');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (34, 7, 'IDENTICAL', NULL, 1, 'Physical value equals internal value');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (35, 7, 'FORM', NULL, 2, 'Formula-based conversion');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (36, 7, 'LINEAR', NULL, 3, 'Linear conversion using COEFFS_LINEAR');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (37, 7, 'RAT_FUNC', NULL, 4, 'Rational function conversion using COEFFS');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (38, 7, 'TAB_INTP', NULL, 5, 'Lookup table conversion with interpolation');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (39, 7, 'TAB_NOINTP', NULL, 6, 'Lookup table conversion without interpolation');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (40, 7, 'TAB_VERB', NULL, 7, 'Verbal lookup table conversion');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (41, 8, 'EEPROM', NULL, 1, 'Electrically erasable programmable read-only memory');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (42, 8, 'EPROM', NULL, 2, 'Erasable programmable read-only memory');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (43, 8, 'FLASH', NULL, 3, 'Flash memory');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (44, 8, 'RAM', NULL, 4, 'Random access memory');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (45, 8, 'ROM', NULL, 5, 'Read-only memory');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (46, 8, 'REGISTER', NULL, 6, 'CPU register space');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (47, 8, 'NOT_IN_ECU', NULL, 7, 'Data exists in the HEX file and calibration database but not in ECU memory');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (48, 9, 'INTERN', NULL, 1, 'Memory region is internal to the ECU');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (49, 9, 'EXTERN', NULL, 2, 'Memory region is external to the ECU');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (50, 10, 'CALIBRATION', NULL, 1, 'Object can be calibrated');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (51, 10, 'NO_CALIBRATION', NULL, 2, 'Object cannot be calibrated');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (52, 10, 'NOT_IN_MCD_SYSTEM', NULL, 3, 'Object is not available through the MCD system');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (53, 10, 'OFFLINE_CALIBRATION', NULL, 4, 'Object can only be calibrated offline');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (54, 11, 'ABSOLUTE', NULL, 1, 'Axis points stored as absolute values');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (55, 11, 'DIFFERENCE', NULL, 2, 'Axis points stored as differences from the previous value');
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (56, 14, 'CURVE_AXIS', NULL, 1, NULL);
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (57, 14, 'COM_AXIS', NULL, 2, NULL);
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (58, 14, 'FIX_AXIS', NULL, 3, NULL);
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (59, 14, 'RES_AXIS', NULL, 4, NULL);
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (60, 14, 'STD_AXIS', NULL, 5, NULL);
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (61, 15, 'ON_USER_REQUEST', NULL, 1, NULL);
INSERT INTO "enum_values" ("id", "enum_type_id", "name", "value", "ordinal", "description") VALUES (62, 15, 'ON_CHANGE', NULL, 2, NULL);
COMMIT;
